
spring.application.name=rewards-service
spring.datasource.url=jdbc:h2:mem:rewardsdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.data-locations=classpath:data.sql
spring.h2.console.enabled=true

#Rewards Strategy Configuration
retail.rewards.limit.low=50
retail.rewards.limit.high=100
retail.rewards.multiplier.between=1
retail.rewards.multiplier.above-high=2
retail.rewards.reward-months=3

logging.file.name=logs/rewards-application.log
logging.level.com.retail.rewards=DEBUG

